In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

pd.options.display.max_rows = 1000
pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings('ignore')

In [27]:
df = pd.read_csv('TESTS_ball_by_ball.csv')

In [28]:
def player_out(player_dismissed):
    if type(player_dismissed) == str:
        return 1
    else:
        return 0

In [29]:
df['Player_out'] = df.apply(lambda x: player_out(x['player_dismissed']), axis = 1)

In [30]:
def is_bowler_wk(wicket_type, player_dismissed):
    if type(player_dismissed) == str:
        if wicket_type not in ('run out','hit wicket','retired hurt',0):
            return 1
        else:
            return 0
    
    else:
        return 0

In [31]:
df['Bowler_wk'] = df.apply(lambda x: is_bowler_wk(x['wicket_type'], x['player_dismissed']), axis = 1)

In [32]:
    df['is_dot'] = df.runs_off_bat.apply(lambda x: 1 if x == 0 else 0)
    df['is_one'] = df.runs_off_bat.apply(lambda x: 1 if x == 1 else 0)
    df['is_two'] = df.runs_off_bat.apply(lambda x: 1 if x == 2 else 0)
    df['is_three'] = df.runs_off_bat.apply(lambda x: 1 if x == 3 else 0)
    df['is_four'] = df.runs_off_bat.apply(lambda x: 1 if x == 4 else 0)
    df['is_six'] = df.runs_off_bat.apply(lambda x: 1 if x == 6 else 0)

In [33]:
df.season.unique()

array(['2003/04', '2004', '2004/05', '2005', '2005/06', '2006', '2006/07',
       '2007', '2007/08', '2008', '2008/09', '2009', '2009/10', '2010',
       '2010/11', '2011', '2011/12', '2012', '2012/13', '2013', '2013/14',
       '2014', '2014/15', '2015', 2015, '2015/16', '2016', '2016/17',
       '2017', '2017/18', '2018', '2018/19', '2019', '2019/20', '2020',
       '2020/21', '2021'], dtype=object)

In [34]:
Virat = df[df.striker == 'V Kohli']
Virat.head(1)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,Player_out,Bowler_wk,is_dot,is_one,is_two,is_three,is_four,is_six
481044,489226,2011,2011-06-20,"Sabina Park, Kingston",3,30.3,India,West Indies,V Kohli,R Dravid,D Bishoo,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0,0,0,0

In [35]:
Virat = Virat[Virat['season'].isin(['2016','2016/17','2017','2017/18','2018','2018/19','2019','2019/20'])]

# isin function is used to filter out values from a particular column

In [36]:
Virat.match_id.unique()

array([1022593, 1022595, 1022597, 1030213, 1030215, 1030217, 1034809,
       1034811, 1034813, 1034815, 1034817, 1041761, 1062573, 1062574,
       1062575, 1109602, 1109603, 1109604, 1122723, 1122724, 1122725,
       1122276, 1122277, 1122278, 1119549, 1119550, 1119551, 1119552,
       1119553, 1157752, 1157753, 1144993, 1144994, 1144995, 1144996,
       1188628, 1188629, 1187007, 1187008, 1187009, 1187016, 1187017,
       1187685, 1187686], dtype=int64)

In [37]:
Virat.tail()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,bowler,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,Player_out,Bowler_wk,is_dot,is_one,is_two,is_three,is_four,is_six
1254990,1187686,2019/20,2020-02-29,Hagley Oval,3,9.2,India,New Zealand,V Kohli,CA Pujara,TA Boult,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0,0,0,0
1254991,1187686,2019/20,2020-02-29,Hagley Oval,3,9.3,India,New Zealand,V Kohli,CA Pujara,TA Boult,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0,0,0,0
1254992,1187686,2019/20,2020-02-29,Hagley Oval,3,9.4,India,New Zealand,V Kohli,CA Pujara,TA Boult,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0,0,0,0
1254993,1187686,2019/20,2020-02-29,Hagley Oval,3,9.5,India,New Zealand,V Kohli,CA Pujara,TA Boult,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0,0,0,0
1254994,1187686,2019/20,2020-02-29,Hagley Oval,3,9.6,India,New Zealand,V Kohli,CA Pujara,TA Boult,0,4,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0,0,0,0

## Phases of Play(2016-2019)

### Match 1

In [46]:
Virat.groupby(['match_id','innings'])['runs_off_bat'].sum().to_frame()

                  runs_off_bat
match_id innings
1022593  1                 200
1022595  2                  44
1022597  1                   3
         3                   4
1030213  1                   9
         3                  18
1030215  1                   9
         3                  45
1030217  1                 211
         3                  17
1034809  2                  40
         4                  49
1034811  1                 167
         3                  81
1034813  2                  62
         4                   6
1034815  2                 235
1034817  2                  15
1041761  1                 204
         3                  38
1062573  2                   0
         4                  13
1062574  1                  12
         3                  15
1062575  2                   6
1109602  1                   3
         3                 103
1109603  1                  13
1109604  1                  42
1119549  2                 149
         4                  51
1119550  1                  23
         3                  17
1119551  1                  97
         3                 103
1119552  2                  46
         4                  58
1119553  2                  49
         4                   0
1122276  2                   5
         4                  28
1122277  2                 153
         4                   5
1122278  1                  54
         3                  41
1122723  1                   0
         3                 104
1122724  2                 213
1122725  1                 243
         3                  50
1144993  1                   3
         3                  34
1144994  2                 123
         4                  17
1144995  1                  82
         3                   0
1144996  1                  23
1157752  1                 139
1157753  2                  45
1187007  1                  20
         3                  31
1187008  1                 254
1187009  1                  12
1187016  2                   0
1187017  2                 136
1187685  1                   2
         3                  19
1187686  1                   3
         3                  14
1188628  1                   9
         3                  51
1188629  1                  76
         3                   0

In [47]:
Virat_match_1 = Virat[Virat.match_id == 1022593]

In [48]:
Virat_match_1 = Virat_match_1.sort_values(by = 'ball')
Virat_match_1['cumsum_balls'] = [i for i in range(1, len(Virat_match_1) + 1)]

In [49]:
def Phases_of_play(cumsum_balls):
     if cumsum_balls < 25:
        return 'First 25 balls'
     elif cumsum_balls < 50:
        return 'Between 25-50 Balls'
     elif cumsum_balls < 75:
        return 'Between 50-75 Balls'
     elif cumsum_balls < 100:
        return 'Between 75-100 Balls'
     elif cumsum_balls < 125:
        return 'Between 100-125 Balls'
     elif cumsum_balls < 150:
        return 'Between 125-150 Balls'
     elif cumsum_balls < 175:
        return 'Between 150-175 Balls'
     elif cumsum_balls < 200:
        return 'Between 175-200 Balls'
     elif cumsum_balls < 225:
        return 'Between 200-225 Balls'
     elif cumsum_balls < 250:
        return 'Between 225-250 Balls'
     elif cumsum_balls < 275:
        return 'Between 250-275 Balls'
     elif cumsum_balls < 300:
        return 'Between 275-300 Balls'
     elif cumsum_balls < 325:
        return 'Between 300-325 Balls'
     elif cumsum_balls < 350:
        return 'Between 325-350 Balls'
     elif cumsum_balls < 375:
        return 'Between 350-375 Balls'
     elif cumsum_balls < 400:
        return 'Between 375-400 Balls'
     elif cumsum_balls < 425:
        return 'Between 400-425 Balls'
     elif cumsum_balls < 450:
        return 'Between 425-450 Balls'
     elif cumsum_balls < 475:
        return 'Between 450-475 Balls'
     elif cumsum_balls < 500:
        return 'Between 475-500 Balls'

In [50]:
Virat_match_1['Phases'] = Virat_match_1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)

In [51]:
Virat_match_1 = Virat_match_1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

In [52]:
Virat_match_1

,match_id,innings,bowling_team,runs_off_bat,ball,is_dot,is_four,is_six,cumsum_balls,Phases,Player_out
910079,1022593,1,West Indies,0,27.5,1,0,0,1,First 25 balls,0
910078,1022593,1,West Indies,0,27.6,1,0,0,2,First 25 balls,0
910073,1022593,1,West Indies,3,28.5,0,0,0,3,First 25 balls,0
910071,1022593,1,West Indies,0,29.1,1,0,0,4,First 25 balls,0
910070,1022593,1,West Indies,0,29.2,1,0,0,5,First 25 balls,0
910069,1022593,1,West Indies,0,29.3,1,0,0,6,First 25 balls,0
910068,1022593,1,West Indies,4,29.4,0,1,0,7,First 25 balls,0
910067,1022593,1,West Indies,1,29.5,0,0,0,8,First 25 balls,0
910066,1022593,1,West Indies,4,30.1,0,1,0,9,First 25 balls,0
910064,1022593,1,West Indies,0,30.2,1,0,0,10,First 25 balls,0
910063,1022593,1,West Indies,0,30.3,1,0,0,11,First 25 balls,0
910062,1022593,1,West Indies,0,30.4,1,0,0,12,First 25 balls,0
910061,1022593,1,West Indies,0,30.5,1,0,0,13,First 25 balls,0
910060,1022593,1,West Indies,0,30.6,1,0,0,14,First 25 balls,0
910058,1022593,1,West Indies,0,31.2,1,0,0,15,First 25 balls,0
910057,1022593,1,West Indies,0,31.3,1,0,0,16,First 25 balls,0
910056,1022593,1,West Indies,0,31.4,1,0,0,17,First 25 balls,0
910055,1022593,1,West Indies,1,31.5,0,0,0,18,First 25 balls,0
910051,1022593,1,West Indies,0,32.3,1,0,0,19,First 25 balls,0
910017,1022593,1,West Indies,1,32.4,0,0,0,20,First 25 balls,0
909982,1022593,1,West Indies,1,33.1,0,0,0,21,First 25 balls,0
909978,1022593,1,West Indies,2,33.4,0,0,0,22,First 25 balls,0
909977,1022593,1,West Indies,0,33.5,1,0,0,23,First 25 balls,0
909976,1022593,1,West Indies,1,33.6,0,0,0,24,First 25 balls,0
909975,1022593,1,West Indies,0,34.1,1,0,0,25,Between 25-50 Balls,0
909974,1022593,1,West Indies,0,34.2,1,0,0,26,Between 25-50 Balls,0
909969,1022593,1,West Indies,0,35.1,1,0,0,27,Between 25-50 Balls,0
909968,1022593,1,West Indies,0,35.2,1,0,0,28,Between 25-50 Balls,0
909967,1022593,1,West Indies,0,35.3,1,0,0,29,Between 25-50 Balls,0
909966,1022593,1,West Indies,1,35.4,0,0,0,30,Between 25-50 Balls,0
909963,1022593,1,West Indies,0,36.1,1,0,0,31,Between 25-50 Balls,0
909962,1022593,1,West Indies,1,36.2,0,0,0,32,Between 25-50 Balls,0
909957,1022593,1,West Indies,0,37.1,1,0,0,33,Between 25-50 Balls,0
909956,1022593,1,West Indies,2,37.2,0,0,0,34,Between 25-50 Balls,0
909955,1022593,1,West Indies,0,37.3,1,0,0,35,Between 25-50 Balls,0
909954,1022593,1,West Indies,0,37.4,1,0,0,36,Between 25-50 Balls,0
909953,1022593,1,West Indies,0,37.5,1,0,0,37,Between 25-50 Balls,0
909952,1022593,1,West Indies,0,37.6,1,0,0,38,Between 25-50 Balls,0
910011,1022593,1,West Indies,0,39.1,1,0,0,39,Between 25-50 Balls,0
910010,1022593,1,West Indies,2,39.2,0,0,0,40,Between 25-50 Balls,0
910009,1022593,1,West Indies,0,39.3,1,0,0,41,Between 25-50 Balls,0
910008,1022593,1,West Indies,1,39.4,0,0,0,42,Between 25-50 Balls,0
910006,1022593,1,West Indies,1,39.6,0,0,0,43,Between 25-50 Balls,0
910005,1022593,1,West Indies,0,40.1,1,0,0,44,Between 25-50 Balls,0
910004,1022593,1,West Indies,3,40.2,0,0,0,45,Between 25-50 Balls,0
909999,1022593,1,West Indies,0,41.1,1,0,0,46,Between 25-50 Balls,0
909998,1022593,1,West Indies,0,41.2,1,0,0,47,Between 25-50 Balls,0
909997,1022593,1,West Indies,1,41.3,0,0,0,48,Between 25-50 Balls,0
909995,1022593,1,West Indies,0,41.5,1,0,0,49,Between 25-50 Balls,0
909994,1022593,1,West Indies,0,41.6,1,0,0,50,Between 50-75 Balls,0
909987,1022593,1,West Indies,0,43.1,1,0,0,51,Between 50-75 Balls,0
909986,1022593,1,West Indies,0,43.2,1,0,0,52,Between 50-75 Balls,0
909985,1022593,1,West Indies,1,43.3,0,0,0,53,Between 50-75 Balls,0
909683,1022593,1,West Indies,2,44.1,0,0,0,54,Between 50-75 Balls,0
909647,1022593,1,West Indies,0,44.2,1,0,0,55,Between 50-75 Balls,0
909646,1022593,1,West Indies,0,44.3,1,0,0,56,Between 50-75 Balls,0
909645,1022593,1,West Indies,1,44.4,0,0,0,57,Between 50-75 Balls,0
909642,1022593,1,West Indies,0,45.1,1,0,0,58,Between 50-75 Balls,0
909641,1022593,1,West Indies,0,45.2,1,0,0,59,Between 50-75 Balls,0
909640,1022593,1,West Indies,1,45.3,0,0,0,60,Between 50-75 Balls,0
909636,1022593,1,West Indies,0,46.1,1,0,0,61,Between 50-75 Balls,0
909635,1022593,1,West Indies,0,46.2,1,0,0,62,Between 50-75 Balls,0
909634,1022593,1,West Indies,2,46.3,0,0,0,63,Between 50-75 Balls,0
909633,1022593,1,West Indies,0,46.4,1,0,0,64,Between 50-75 Balls,0
909632,1022593,1,West Indies,4,46.5,0,1,0,65,Between 50-75 Balls,0
909631,1022593,1,West Indies,0,46.6,1,0,0,66,Between 50-75 Balls,0
909628,1022593,1,West Indies,4,47.3,0,1,0,67,Between 50-75 Balls,0
909627,1022593,1,West Indies,0,47.4,1,0,0,68,Between 50-75 Balls,0
909626,1022593,1,West Indies,0,47.5,1,0,0,69,Between 50-75 Balls,0
909625,1022593,1,West Indies,1,47.6,0,0,0,70,Between 50-75 Balls,0
909624,1022593,1,West Indies,0,48.1,1,0,0,71,Between 50-75 Balls,0
909623,1022593,1,West Indies,0,48.2,1,0,0,72,Between 50-75 Balls,0
909622,1022593,1,West Indies,0,48.3,1,0,0,73,Between 50-75 Balls,0
909621,1022593,1,West Indies,0,48.4,1,0,0,74,Between 50-75 Balls,0
909620,1022593,1,West Indies,4,48.5,0,1,0,75,Between 75-100 Balls,0
909619,1022593,1,West Indies,4,48.6,0,1,0,76,Between 75-100 Balls,0
909651,1022593,1,West Indies,0,49.4,1,0,0,77,Between 75-100 Balls,0
909681,1022593,1,West Indies,0,49.5,1,0,0,78,Between 75-100 Balls,0
909680,1022593,1,West Indies,1,49.6,0,0,0,79,Between 75-100 Balls,0
909679,1022593,1,West Indies,4,50.1,0,1,0,80,Between 75-100 Balls,0
909678,1022593,1,West Indies,0,50.2,1,0,0,81,Between 75-100 Balls,0
909677,1022593,1,West Indies,1,50.3,0,0,0,82,Between 75-100 Balls,0
909673,1022593,1,West Indies,0,51.1,1,0,0,83,Between 75-100 Balls,0
909672,1022593,1,West Indies,0,51.2,1,0,0,84,Between 75-100 Balls,0
909671,1022593,1,West Indies,4,51.3,0,1,0,85,Between 75-100 Balls,0
909670,1022593,1,West Indies,0,51.4,1,0,0,86,Between 75-100 Balls,0
909669,1022593,1,West Indies,0,51.5,1,0,0,87,Between 75-100 Balls,0
909668,1022593,1,West Indies,0,51.6,1,0,0,88,Between 75-100 Balls,0
909682,1022593,1,West Indies,0,51.7,1,0,0,89,Between 75-100 Balls,0
909661,1022593,1,West Indies,0,52.6,1,0,0,90,Between 75-100 Balls,0
909654,1022593,1,West Indies,1,54.1,0,0,0,91,Between 75-100 Balls,0
909576,1022593,1,West Indies,0,56.1,1,0,0,92,Between 75-100 Balls,0
909575,1022593,1,West Indies,1,56.2,0,0,0,93,Between 75-100 Balls,0
909573,1022593,1,West Indies,0,56.4,1,0,0,94,Between 75-100 Balls,0
909572,1022593,1,West Indies,1,56.5,0,0,0,95,Between 75-100 Balls,0
909570,1022593,1,West Indies,0,57.1,1,0,0,96,Between 75-100 Balls,0
909569,1022593,1,West Indies,2,57.2,0,0,0,97,Between 75-100 Balls,0
909568,1022593,1,West Indies,1,57.3,0,0,0,98,Between 75-100 Balls,0
909564,1022593,1,West Indies,1,58.1,0,0,0,99,Between 75-100 Balls,0
909560,1022593,1,West Indies,1,58.5,0,0,0,100,Between 100-125 Balls,0
909558,1022593,1,West Indies,0,59.1,1,0,0,101,Between 100-125 Balls,0
909557,1022593,1,West Indies,2,59.2,0,0,0,102,Between 100-125 Balls,0
909556,1022593,1,West Indies,0,59.3,1,0,0,103,Between 100-125 Balls,0
909555,1022593,1,West Indies,0,59.4,1,0,0,104,Between 100-125 Balls,0
909554,1022593,1,West Indies,1,59.5,0,0,0,105,Between 100-125 Balls,0
909582,1022593,1,West Indies,1,60.1,0,0,0,106,Between 100-125 Balls,0
909612,1022593,1,West Indies,0,61.1,1,0,0,107,Between 100-125 Balls,0
909611,1022593,1,West Indies,4,61.2,0,1,0,108,Between 100-125 Balls,0
909610,1022593,1,West Indies,0,61.3,1,0,0,109,Between 100-125 Balls,0
909609,1022593,1,West Indies,1,61.4,0,0,0,110,Between 100-125 Balls,0
909606,1022593,1,West Indies,1,62.1,0,0,0,111,Between 100-125 Balls,0
909603,1022593,1,West Indies,0,62.4,1,0,0,112,Between 100-125 Balls,0
909600,1022593,1,West Indies,0,63.1,1,0,0,113,Between 100-125 Balls,0
909599,1022593,1,West Indies,1,63.2,0,0,0,114,Between 100-125 Balls,0
909594,1022593,1,West Indies,0,64.1,1,0,0,115,Between 100-125 Balls,0
909593,1022593,1,West Indies,0,64.2,1,0,0,116,Between 100-125 Balls,0
909592,1022593,1,West Indies,4,64.3,0,1,0,117,Between 100-125 Balls,0
909591,1022593,1,West Indies,0,64.4,1,0,0,118,Between 100-125 Balls,0
909590,1022593,1,West Indies,4,64.5,0,1,0,119,Between 100-125 Balls,0
909589,1022593,1,West Indies,0,64.6,1,0,0,120,Between 100-125 Balls,0
909586,1022593,1,West Indies,1,65.3,0,0,0,121,Between 100-125 Balls,0
909684,1022593,1,West Indies,0,65.5,1,0,0,122,Between 100-125 Balls,0
909799,1022593,1,West Indies,1,65.6,0,0,0,123,Between 100-125 Balls,0
909685,1022593,1,West Indies,0,66.1,1,0,0,124,Between 100-125 Balls,0
909780,1022593,1,West Indies,2,66.2,0,0,0,125,Between 125-150 Balls,0
909779,1022593,1,West Indies,0,66.3,1,0,0,126,Between 125-150 Balls,0
909778,1022593,1,West Indies,2,66.4,0,0,0,127,Between 125-150 Balls,0
909777,1022593,1,West Indies,0,66.5,1,0,0,128,Between 125-150 Balls,0
909776,1022593,1,West Indies,1,66.6,0,0,0,129,Between 125-150 Balls,0
909775,1022593,1,West Indies,1,67.1,0,0,0,130,Between 125-150 Balls,0
909769,1022593,1,West Indies,0,68.1,1,0,0,131,Between 125-150 Balls,0
909768,1022593,1,West Indies,0,68.2,1,0,0,132,Between 125-150 Balls,0
909767,1022593,1,West Indies,0,68.3,1,0,0,133,Between 125-150 Balls,0
909766,1022593,1,West Indies,1,68.4,0,0,0,134,Between 125-150 Balls,0
909763,1022593,1,West Indies,0,69.1,1,0,0,135,Between 125-150 Balls,0
909762,1022593,1,West Indies,0,69.2,1,0,0,136,Between 125-150 Balls,0
909761,1022593,1,West Indies,0,69.3,1,0,0,137,Between 125-150 Balls,0
909760,1022593,1,West Indies,0,69.4,1,0,0,138,Between 125-150 Balls,0
909759,1022593,1,West Indies,4,69.5,0,1,0,139,Between 125-150 Balls,0
909758,1022593,1,West Indies,4,69.6,0,1,0,140,Between 125-150 Balls,0
909781,1022593,1,West Indies,4,71.1,0,1,0,141,Between 125-150 Balls,0
909782,1022593,1,West Indies,0,71.2,1,0,0,142,Between 125-150 Balls,0
909783,1022593,1,West Indies,0,71.3,1,0,0,143,Between 125-150 Balls,0
909784,1022593,1,West Indies,0,71.4,1,0,0,144,Between 125-150 Balls,0
909814,1022593,1,West Indies,1,71.5,0,0,0,145,Between 125-150 Balls,0
909812,1022593,1,West Indies,1,72.1,0,0,0,146,Between 125-150 Balls,0
909810,1022593,1,West Indies,0,72.3,1,0,0,147,Between 125-150 Balls,0
909809,1022593,1,West Indies,0,72.4,1,0,0,148,Between 125-150 Balls,0
909808,1022593,1,West Indies,0,72.5,1,0,0,149,Between 125-150 Balls,0
909807,1022593,1,West Indies,0,72.6,1,0,0,150,Between 150-175 Balls,0
909803,1022593,1,West Indies,0,73.4,1,0,0,151,Between 150-175 Balls,0
909802,1022593,1,West Indies,2,73.5,0,0,0,152,Between 150-175 Balls,0
909801,1022593,1,West Indies,1,73.6,0,0,0,153,Between 150-175 Balls,0
909815,1022593,1,West Indies,0,74.1,1,0,0,154,Between 150-175 Balls,0
909800,1022593,1,West Indies,1,74.2,0,0,0,155,Between 150-175 Balls,0
909794,1022593,1,West Indies,0,75.1,1,0,0,156,Between 150-175 Balls,0
909793,1022593,1,West Indies,2,75.2,0,0,0,157,Between 150-175 Balls,0
909792,1022593,1,West Indies,0,75.3,1,0,0,158,Between 150-175 Balls,0
909791,1022593,1,West Indies,0,75.4,1,0,0,159,Between 150-175 Balls,0
909790,1022593,1,West Indies,4,75.5,0,1,0,160,Between 150-175 Balls,0
909789,1022593,1,West Indies,0,75.6,1,0,0,161,Between 150-175 Balls,0
909749,1022593,1,West Indies,0,77.1,1,0,0,162,Between 150-175 Balls,0
909716,1022593,1,West Indies,0,77.2,1,0,0,163,Between 150-175 Balls,0
909714,1022593,1,West Indies,1,77.3,0,0,0,164,Between 150-175 Balls,0
909710,1022593,1,West Indies,0,78.1,1,0,0,165,Between 150-175 Balls,0
909709,1022593,1,West Indies,1,78.2,0,0,0,166,Between 150-175 Balls,0
909705,1022593,1,West Indies,0,78.6,1,0,0,167,Between 150-175 Balls,0
909702,1022593,1,West Indies,1,79.3,0,0,0,168,Between 150-175 Balls,0
909696,1022593,1,West Indies,1,80.3,0,0,0,169,Between 150-175 Balls,0
909692,1022593,1,West Indies,0,81.1,1,0,0,170,Between 150-175 Balls,0
909691,1022593,1,West Indies,0,81.2,1,0,0,171,Between 150-175 Balls,0
909690,1022593,1,West Indies,0,81.3,1,0,0,172,Between 150-175 Balls,0
909689,1022593,1,West Indies,4,81.4,0,1,0,173,Between 150-175 Balls,0
909688,1022593,1,West Indies,1,81.5,0,0,0,174,Between 150-175 Balls,0
909686,1022593,1,West Indies,1,82.1,0,0,0,175,Between 175-200 Balls,0
909717,1022593,1,West Indies,0,82.3,1,0,0,176,Between 175-200 Balls,0
909748,1022593,1,West Indies,1,82.4,0,0,0,177,Between 175-200 Balls,0
909746,1022593,1,West Indies,0,83.1,1,0,0,178,Between 175-200 Balls,0
909745,1022593,1,West Indies,1,83.2,0,0,0,179,Between 175-200 Balls,0
909740,1022593,1,West Indies,0,84.1,1,0,0,180,Between 175-200 Balls,0
909739,1022593,1,West Indies,0,84.2,1,0,0,181,Between 175-200 Balls,0
909738,1022593,1,West Indies,0,84.3,1,0,0,182,Between 175-200 Balls,0
909737,1022593,1,West Indies,0,84.4,1,0,0,183,Between 175-200 Balls,0
909736,1022593,1,West Indies,1,84.5,0,0,0,184,Between 175-200 Balls,0
909734,1022593,1,West Indies,0,85.1,1,0,0,185,Between 175-200 Balls,0
909733,1022593,1,West Indies,0,85.2,1,0,0,186,Between 175-200 Balls,0
909732,1022593,1,West Indies,1,85.3,0,0,0,187,Between 175-200 Balls,0
909728,1022593,1,West Indies,1,86.1,0,0,0,188,Between 175-200 Balls,0
909726,1022593,1,West Indies,0,86.3,1,0,0,189,Between 175-200 Balls,0
909725,1022593,1,West Indies,0,86.4,1,0,0,190,Between 175-200 Balls,0
909724,1022593,1,West Indies,1,86.5,0,0,0,191,Between 175-200 Balls,0
909720,1022593,1,West Indies,0,87.3,1,0,0,192,Between 175-200 Balls,0
909719,1022593,1,West Indies,1,87.4,0,0,0,193,Between 175-200 Balls,0
910083,1022593,1,West Indies,1,88.1,0,0,0,194,Between 175-200 Balls,0
910441,1022593,1,West Indies,0,89.1,1,0,0,195,Between 175-200 Balls,0
910440,1022593,1,West Indies,0,89.2,1,0,0,196,Between 175-200 Balls,0
910439,1022593,1,West Indies,1,89.3,0,0,0,197,Between 175-200 Balls,0
910435,1022593,1,West Indies,0,90.1,1,0,0,198,Between 175-200 Balls,0
910434,1022593,1,West Indies,2,90.2,0,0,0,199,Between 175-200 Balls,0
910433,1022593,1,West Indies,1,90.3,0,0,0,200,Between 200-225 Balls,0
910429,1022593,1,West Indies,2,91.1,0,0,0,201,Between 200-225 Balls,0
910428,1022593,1,West Indies,0,91.2,1,0,0,202,Between 200-225 Balls,0
910427,1022593,1,West Indies,0,91.3,1,0,0,203,Between 200-225 Balls,0
910426,1022593,1,West Indies,0,91.4,1,0,0,204,Between 200-225 Balls,0
910425,1022593,1,West Indies,1,91.5,0,0,0,205,Between 200-225 Balls,0
910423,1022593,1,West Indies,0,92.1,1,0,0,206,Between 200-225 Balls,0
910422,1022593,1,West Indies,0,92.2,1,0,0,207,Between 200-225 Balls,0
910421,1022593,1,West Indies,4,92.3,0,1,0,208,Between 200-225 Balls,0
910420,1022593,1,West Indies,1,92.4,0,0,0,209,Between 200-225 Balls,0
910417,1022593,1,West Indies,0,93.1,1,0,0,210,Between 200-225 Balls,0
910446,1022593,1,West Indies,0,93.2,1,0,0,211,Between 200-225 Balls,0
910447,1022593,1,West Indies,0,93.3,1,0,0,212,Between 200-225 Balls,0
910448,1022593,1,West Indies,0,93.4,1,0,0,213,Between 200-225 Balls,0
910449,1022593,1,West Indies,0,93.5,1,0,0,214,Between 200-225 Balls,0
910479,1022593,1,West Indies,0,93.6,1,0,0,215,Between 200-225 Balls,0
910473,1022593,1,West Indies,0,94.6,1,0,0,216,Between 200-225 Balls,0
910472,1022593,1,West Indies,0,94.7,1,0,0,217,Between 200-225 Balls,0
910465,1022593,1,West Indies,4,96.1,0,1,0,218,Between 200-225 Balls,0
910463,1022593,1,West Indies,0,96.2,1,0,0,219,Between 200-225 Balls,0
910462,1022593,1,West Indies,0,96.3,1,0,0,220,Between 200-225 Balls,0
910461,1022593,1,West Indies,4,96.4,0,1,0,221,Between 200-225 Balls,0
910460,1022593,1,West Indies,0,96.5,1,0,0,222,Between 200-225 Balls,0
910459,1022593,1,West Indies,0,96.6,1,0,0,223,Between 200-225 Balls,0
910451,1022593,1,West Indies,0,98.1,1,0,0,224,Between 200-225 Balls,0
910450,1022593,1,West Indies,0,98.2,1,0,0,225,Between 225-250 Balls,0
910416,1022593,1,West Indies,1,98.3,0,0,0,226,Between 225-250 Balls,0
910379,1022593,1,West Indies,0,99.1,1,0,0,227,Between 225-250 Balls,0
910378,1022593,1,West Indies,0,99.2,1,0,0,228,Between 225-250 Balls,0
910377,1022593,1,West Indies,0,99.3,1,0,0,229,Between 225-250 Balls,0
910376,1022593,1,West Indies,0,99.4,1,0,0,230,Between 225-250 Balls,0
910375,1022593,1,West Indies,0,99.5,1,0,0,231,Between 225-250 Balls,0
910374,1022593,1,West Indies,0,99.6,1,0,0,232,Between 225-250 Balls,0
910367,1022593,1,West Indies,0,101.1,1,0,0,233,Between 225-250 Balls,0
910366,1022593,1,West Indies,0,101.2,1,0,0,234,Between 225-250 Balls,0
910365,1022593,1,West Indies,0,101.3,1,0,0,235,Between 225-250 Balls,0
910364,1022593,1,West Indies,0,101.4,1,0,0,236,Between 225-250 Balls,0
910363,1022593,1,West Indies,0,101.5,1,0,0,237,Between 225-250 Balls,0
910362,1022593,1,West Indies,4,101.6,0,1,0,238,Between 225-250 Balls,0
910357,1022593,1,West Indies,1,102.5,0,0,0,239,Between 225-250 Balls,0
910355,1022593,1,West Indies,0,103.1,1,0,0,240,Between 225-250 Balls,0
910354,1022593,1,West Indies,0,103.2,1,0,0,241,Between 225-250 Balls,0
910353,1022593,1,West Indies,0,103.3,1,0,0,242,Between 225-250 Balls,0
910352,1022593,1,West Indies,0,103.4,1,0,0,243,Between 225-250 Balls,0
910351,1022593,1,West Indies,0,103.5,1,0,0,244,Between 225-250 Balls,0
910615,1022593,1,West Indies,0,103.6,1,0,0,245,Between 225-250 Balls,0
910382,1022593,1,West Indies,4,104.2,0,1,0,246,Between 225-250 Balls,0
910413,1022593,1,West Indies,1,104.3,0,0,0,247,Between 225-250 Balls,0
910410,1022593,1,West Indies,0,105.1,1,0,0,248,Between 225-250 Balls,0
910409,1022593,1,West Indies,4,105.2,0,1,0,249,Between 225-250 Balls,0
910408,1022593,1,West Indies,0,105.3,1,0,0,250,Between 250-275 Balls,0
910407,1022593,1,West Indies,0,105.4,1,0,0,251,Between 250-275 Balls,0
910406,1022593,1,West Indies,0,105.5,1,0,0,252,Between 250-275 Balls,0
910405,1022593,1,West Indies,1,105.6,0,0,0,253,Between 250-275 Balls,0
910404,1022593,1,West Indies,0,106.1,1,0,0,254,Between 250-275 Balls,0
910403,1022593,1,West Indies,0,106.2,1,0,0,255,Between 250-275 Balls,0
910402,1022593,1,West Indies,1,106.3,0,0,0,256,Between 250-275 Balls,0
910398,1022593,1,West Indies,1,107.1,0,0,0,257,Between 250-275 Balls,0
910392,1022593,1,West Indies,4,108.1,0,1,0,258,Between 250-275 Balls,0
910391,1022593,1,West Indies,0,108.2,1,0,0,259,Between 250-275 Balls,0
910390,1022593,1,West Indies,0,108.3,1,0,0,260,Between 250-275 Balls,0
910389,1022593,1,West Indies,0,108.4,1,0,0,261,Between 250-275 Balls,0
910388,1022593,1,West Indies,1,108.5,0,0,0,262,Between 250-275 Balls,0
910386,1022593,1,West Indies,0,109.1,1,0,0,263,Between 250-275 Balls,0
910385,1022593,1,West Indies,0,109.2,1,0,0,264,Between 250-275 Balls,0
910384,1022593,1,West Indies,4,109.3,0,1,0,265,Between 250-275 Balls,0
910464,1022593,1,West Indies,0,109.4,1,0,0,266,Between 250-275 Balls,0
910481,1022593,1,West Indies,1,109.5,0,0,0,267,Between 250-275 Balls,0
910483,1022593,1,West Indies,1,110.1,0,0,0,268,Between 250-275 Balls,0
910577,1022593,1,West Indies,1,110.4,0,0,0,269,Between 250-275 Balls,0
910568,1022593,1,West Indies,1,112.1,0,0,0,270,Between 250-275 Balls,0
910563,1022593,1,West Indies,0,112.6,1,0,0,271,Between 250-275 Balls,0
910561,1022593,1,West Indies,1,113.2,0,0,0,272,Between 250-275 Balls,0
910556,1022593,1,West Indies,0,114.1,1,0,0,273,Between 250-275 Balls,0
910555,1022593,1,West Indies,1,114.2,0,0,0,274,Between 250-275 Balls,0
910552,1022593,1,West Indies,0,114.5,1,0,0,275,Between 275-300 Balls,0
910551,1022593,1,West Indies,0,114.6,1,0,0,276,Between 275-300 Balls,0
910605,1022593,1,West Indies,1,117.1,0,0,0,277,Between 275-300 Balls,0
910602,1022593,1,West Indies,2,117.4,0,0,0,278,Between 275-300 Balls,0
910601,1022593,1,West Indies,0,117.5,1,0,0,279,Between 275-300 Balls,0
910600,1022593,1,West Indies,1,117.6,0,0,0,280,Between 275-300 Balls,0
910614,1022593,1,West Indies,1,118.1,0,0,0,281,Between 275-300 Balls,0
910593,1022593,1,West Indies,0,119.1,1,0,0,282,Between 275-300 Balls,0
910592,1022593,1,West Indies,0,119.2,1,0,0,283,Between 275-300 Balls,1

### Match 2

In [53]:
Virat_match_2 = Virat[Virat.match_id == 1022595]

Virat_match_2 = Virat_match_2.sort_values(by = 'ball')
Virat_match_2['cumsum_balls'] = [i for i in range(1, len(Virat_match_2) + 1)]

Virat_match_2['Phases'] = Virat_match_2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)

Virat_match_2 = Virat_match_2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 3

In [54]:
Virat_match_3 = Virat[Virat.match_id == 1022597]

Virat_match_3_inning1 = Virat_match_3[Virat_match_3.innings == 1]
Virat_match_3_inning3 = Virat_match_3[Virat_match_3.innings == 3]

Virat_match_3_inning1 = Virat_match_3_inning1.sort_values(by = 'ball')
Virat_match_3_inning3 = Virat_match_3_inning3.sort_values(by = 'ball')

Virat_match_3_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_3_inning1) + 1)]
Virat_match_3_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_3_inning3) + 1)]

Virat_match_3_inning1['Phases'] = Virat_match_3_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_3_inning3['Phases'] = Virat_match_3_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_3_inning1 = Virat_match_3_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_3_inning3 = Virat_match_3_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 4

In [55]:
Virat_match_4 = Virat[Virat.match_id == 1030213]

Virat_match_4_inning1 = Virat_match_4[Virat_match_4.innings == 1]
Virat_match_4_inning3 = Virat_match_4[Virat_match_4.innings == 3]

Virat_match_4_inning1 = Virat_match_4_inning1.sort_values(by = 'ball')
Virat_match_4_inning3 = Virat_match_4_inning3.sort_values(by = 'ball')

Virat_match_4_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_4_inning1) + 1)]
Virat_match_4_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_4_inning3) + 1)]

Virat_match_4_inning1['Phases'] = Virat_match_4_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_4_inning3['Phases'] = Virat_match_4_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_4_inning1 = Virat_match_4_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_4_inning3 = Virat_match_4_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 5

In [56]:
Virat_match_5 = Virat[Virat.match_id == 1030215]

Virat_match_5_inning1 = Virat_match_5[Virat_match_5.innings == 1]
Virat_match_5_inning3 = Virat_match_5[Virat_match_5.innings == 3]

Virat_match_5_inning1 = Virat_match_5_inning1.sort_values(by = 'ball')
Virat_match_5_inning3 = Virat_match_5_inning3.sort_values(by = 'ball')

Virat_match_5_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_5_inning1) + 1)]
Virat_match_5_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_5_inning3) + 1)]

Virat_match_5_inning1['Phases'] = Virat_match_5_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_5_inning3['Phases'] = Virat_match_5_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_5_inning1 = Virat_match_5_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_5_inning3 = Virat_match_5_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 6

In [57]:
Virat_match_6 = Virat[Virat.match_id == 1030217]

Virat_match_6_inning1 = Virat_match_6[Virat_match_6.innings == 1]
Virat_match_6_inning3 = Virat_match_6[Virat_match_6.innings == 3]

Virat_match_6_inning1 = Virat_match_6_inning1.sort_values(by = 'ball')
Virat_match_6_inning3 = Virat_match_6_inning3.sort_values(by = 'ball')

Virat_match_6_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_6_inning1) + 1)]
Virat_match_6_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_6_inning3) + 1)]

Virat_match_6_inning1['Phases'] = Virat_match_6_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_6_inning3['Phases'] = Virat_match_6_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_6_inning1 = Virat_match_6_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_6_inning3 = Virat_match_6_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 7

In [58]:
Virat_match_7 = Virat[Virat.match_id == 1034809]

Virat_match_7_inning2 = Virat_match_7[Virat_match_7.innings == 2]
Virat_match_7_inning4 = Virat_match_7[Virat_match_7.innings == 4]

Virat_match_7_inning2 = Virat_match_7_inning2.sort_values(by = 'ball')
Virat_match_7_inning4 = Virat_match_7_inning4.sort_values(by = 'ball')

Virat_match_7_inning2['cumsum_balls'] = [i for i in range(1, len(Virat_match_7_inning2) + 1)]
Virat_match_7_inning4['cumsum_balls'] = [i for i in range(1, len(Virat_match_7_inning4) + 1)]

Virat_match_7_inning2['Phases'] = Virat_match_7_inning2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_7_inning4['Phases'] = Virat_match_7_inning4.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_7_inning2 = Virat_match_7_inning2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_7_inning4 = Virat_match_7_inning4[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 8

In [59]:
Virat_match_8 = Virat[Virat.match_id == 1034811]

Virat_match_8_inning1 = Virat_match_8[Virat_match_8.innings == 1]
Virat_match_8_inning3 = Virat_match_8[Virat_match_8.innings == 3]

Virat_match_8_inning1 = Virat_match_8_inning1.sort_values(by = 'ball')
Virat_match_8_inning3 = Virat_match_8_inning3.sort_values(by = 'ball')

Virat_match_8_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_8_inning1) + 1)]
Virat_match_8_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_8_inning3) + 1)]

Virat_match_8_inning1['Phases'] = Virat_match_8_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_8_inning3['Phases'] = Virat_match_8_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_8_inning1 = Virat_match_8_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_8_inning3 = Virat_match_8_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 9

In [60]:
Virat_match_9 = Virat[Virat.match_id == 1034813]

Virat_match_9_inning2 = Virat_match_9[Virat_match_9.innings == 2]
Virat_match_9_inning4 = Virat_match_9[Virat_match_9.innings == 4]

Virat_match_9_inning2 = Virat_match_9_inning2.sort_values(by = 'ball')
Virat_match_9_inning4 = Virat_match_9_inning4.sort_values(by = 'ball')

Virat_match_9_inning2['cumsum_balls'] = [i for i in range(1, len(Virat_match_9_inning2) + 1)]
Virat_match_9_inning4['cumsum_balls'] = [i for i in range(1, len(Virat_match_9_inning4) + 1)]

Virat_match_9_inning2['Phases'] = Virat_match_9_inning2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_9_inning4['Phases'] = Virat_match_9_inning4.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_9_inning2 = Virat_match_9_inning2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_9_inning4 = Virat_match_9_inning4[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 10

In [61]:
Virat_match_10 = Virat[Virat.match_id == 1034815]

Virat_match_10 = Virat_match_10[Virat_match_10.innings == 2]

Virat_match_10 = Virat_match_10.sort_values(by = 'ball')

Virat_match_10['cumsum_balls'] = [i for i in range(1, len(Virat_match_10) + 1)]

Virat_match_10['Phases'] = Virat_match_10.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_10 = Virat_match_10[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 10

In [62]:
Virat_match_11 = Virat[Virat.match_id == 1034817]

Virat_match_11 = Virat_match_11[Virat_match_11.innings == 2]

Virat_match_11 = Virat_match_11.sort_values(by = 'ball')

Virat_match_11['cumsum_balls'] = [i for i in range(1, len(Virat_match_11) + 1)]

Virat_match_11['Phases'] = Virat_match_11.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_11 = Virat_match_11[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 11

In [63]:
Virat_match_11_1 = Virat[Virat.match_id == 1041761]

Virat_match_11_1_inning1 = Virat_match_11_1[Virat_match_11_1.innings == 1]
Virat_match_11_1_inning3 = Virat_match_11_1[Virat_match_11_1.innings == 3]

Virat_match_11_1_inning1 = Virat_match_11_1_inning1.sort_values(by = 'ball')
Virat_match_11_1_inning3 = Virat_match_11_1_inning3.sort_values(by = 'ball')

Virat_match_11_1_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_11_1_inning1) + 1)]
Virat_match_11_1_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_11_1_inning3) + 1)]

Virat_match_11_1_inning1['Phases'] = Virat_match_11_1_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_11_1_inning3['Phases'] = Virat_match_11_1_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_11_1_inning1 = Virat_match_11_1_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_11_1_inning3 = Virat_match_11_1_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 12

In [64]:
Virat_match_12 = Virat[Virat.match_id == 1062573]

Virat_match_12_inning2 = Virat_match_12[Virat_match_12.innings == 2]
Virat_match_12_inning4 = Virat_match_12[Virat_match_12.innings == 4]

Virat_match_12_inning2 = Virat_match_12_inning2.sort_values(by = 'ball')
Virat_match_12_inning4 = Virat_match_12_inning4.sort_values(by = 'ball')

Virat_match_12_inning2['cumsum_balls'] = [i for i in range(1, len(Virat_match_12_inning2) + 1)]
Virat_match_12_inning4['cumsum_balls'] = [i for i in range(1, len(Virat_match_12_inning4) + 1)]

Virat_match_12_inning2['Phases'] = Virat_match_12_inning2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_12_inning4['Phases'] = Virat_match_12_inning4.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_12_inning2 = Virat_match_12_inning2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_12_inning4 = Virat_match_12_inning4[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 13

In [65]:
Virat_match_13 = Virat[Virat.match_id == 1062574]

Virat_match_13_inning1 = Virat_match_13[Virat_match_13.innings == 1]
Virat_match_13_inning3 = Virat_match_13[Virat_match_13.innings == 3]

Virat_match_13_inning1 = Virat_match_13_inning1.sort_values(by = 'ball')
Virat_match_13_inning3 = Virat_match_13_inning3.sort_values(by = 'ball')

Virat_match_13_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_13_inning1) + 1)]
Virat_match_13_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_13_inning3) + 1)]

Virat_match_13_inning1['Phases'] = Virat_match_13_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_13_inning3['Phases'] = Virat_match_13_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_13_inning1 = Virat_match_13_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_13_inning3 = Virat_match_13_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 14

In [66]:
Virat_match_14 = Virat[Virat.match_id == 1062575]

Virat_match_14 = Virat_match_14[Virat_match_14.innings == 2]

Virat_match_14 = Virat_match_14.sort_values(by = 'ball')

Virat_match_14['cumsum_balls'] = [i for i in range(1, len(Virat_match_14) + 1)]

Virat_match_14['Phases'] = Virat_match_14.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_14 = Virat_match_14[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 15

In [67]:
Virat_match_15 = Virat[Virat.match_id == 1109602]

Virat_match_15_inning1 = Virat_match_15[Virat_match_15.innings == 1]
Virat_match_15_inning3 = Virat_match_15[Virat_match_15.innings == 3]

Virat_match_15_inning1 = Virat_match_15_inning1.sort_values(by = 'ball')
Virat_match_15_inning3 = Virat_match_15_inning3.sort_values(by = 'ball')

Virat_match_15_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_15_inning1) + 1)]
Virat_match_15_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_15_inning3) + 1)]

Virat_match_15_inning1['Phases'] = Virat_match_15_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_15_inning3['Phases'] = Virat_match_15_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_15_inning1 = Virat_match_15_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_15_inning3 = Virat_match_15_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 16

In [68]:
Virat_match_16 = Virat[Virat.match_id == 1109603]

Virat_match_16 = Virat_match_16[Virat_match_16.innings == 1]

Virat_match_16 = Virat_match_16.sort_values(by = 'ball')

Virat_match_16['cumsum_balls'] = [i for i in range(1, len(Virat_match_16) + 1)]

Virat_match_16['Phases'] = Virat_match_16.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_16 = Virat_match_16[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 17

In [69]:
Virat_match_17 = Virat[Virat.match_id == 1109604]
Virat_match_17 = Virat_match_17[Virat_match_17.innings == 1]

Virat_match_17 = Virat_match_17.sort_values(by = 'ball')

Virat_match_17['cumsum_balls'] = [i for i in range(1, len(Virat_match_17) + 1)]

Virat_match_17['Phases'] = Virat_match_17.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_17 = Virat_match_17[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 18

In [70]:
Virat_match_18 = Virat[Virat.match_id == 1119549]
Virat_match_18_inning2 = Virat_match_18[Virat_match_18.innings == 2]
Virat_match_18_inning4 = Virat_match_18[Virat_match_18.innings == 4]

Virat_match_18_inning2 = Virat_match_18_inning2.sort_values(by = 'ball')
Virat_match_18_inning4 = Virat_match_18_inning4.sort_values(by = 'ball')

Virat_match_18_inning2['cumsum_balls'] = [i for i in range(1, len(Virat_match_18_inning2) + 1)]
Virat_match_18_inning4['cumsum_balls'] = [i for i in range(1, len(Virat_match_18_inning4) + 1)]

Virat_match_18_inning2['Phases'] = Virat_match_18_inning2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_18_inning4['Phases'] = Virat_match_18_inning4.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_18_inning2 = Virat_match_18_inning2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_18_inning4 = Virat_match_18_inning4[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 19

In [71]:
Virat_match_19 = Virat[Virat.match_id == 1119550]

Virat_match_19_inning1 = Virat_match_19[Virat_match_19.innings == 1]
Virat_match_19_inning3 = Virat_match_19[Virat_match_19.innings == 3]

Virat_match_19_inning1 = Virat_match_19_inning1.sort_values(by = 'ball')
Virat_match_19_inning3 = Virat_match_19_inning3.sort_values(by = 'ball')

Virat_match_19_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_19_inning1) + 1)]
Virat_match_19_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_19_inning3) + 1)]

Virat_match_19_inning1['Phases'] = Virat_match_19_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_19_inning3['Phases'] = Virat_match_19_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_19_inning1 = Virat_match_19_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_19_inning3 = Virat_match_19_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 20

In [72]:
Virat_match_20 = Virat[Virat.match_id == 1119551]
Virat_match_20_inning1 = Virat_match_20[Virat_match_20.innings == 1]
Virat_match_20_inning3 = Virat_match_20[Virat_match_20.innings == 3]

Virat_match_20_inning1 = Virat_match_20_inning1.sort_values(by = 'ball')
Virat_match_20_inning3 = Virat_match_20_inning3.sort_values(by = 'ball')

Virat_match_20_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_20_inning1) + 1)]
Virat_match_20_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_20_inning3) + 1)]

Virat_match_20_inning1['Phases'] = Virat_match_20_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_20_inning3['Phases'] = Virat_match_20_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_20_inning1 = Virat_match_20_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_20_inning3 = Virat_match_20_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 21

In [73]:
Virat_match_21 = Virat[Virat.match_id == 1119552]
Virat_match_21_inning2 = Virat_match_21[Virat_match_21.innings == 2]
Virat_match_21_inning4 = Virat_match_21[Virat_match_21.innings == 4]

Virat_match_21_inning2 = Virat_match_21_inning2.sort_values(by = 'ball')
Virat_match_21_inning4 = Virat_match_21_inning4.sort_values(by = 'ball')

Virat_match_21_inning2['cumsum_balls'] = [i for i in range(1, len(Virat_match_21_inning2) + 1)]
Virat_match_21_inning4['cumsum_balls'] = [i for i in range(1, len(Virat_match_21_inning4) + 1)]

Virat_match_21_inning2['Phases'] = Virat_match_21_inning2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_21_inning4['Phases'] = Virat_match_21_inning4.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_21_inning2 = Virat_match_21_inning2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_21_inning4 = Virat_match_21_inning4[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 22

In [74]:
Virat_match_22 = Virat[Virat.match_id == 1119553]
Virat_match_22_inning2 = Virat_match_22[Virat_match_22.innings == 2]
Virat_match_22_inning4 = Virat_match_22[Virat_match_22.innings == 4]

Virat_match_22_inning2 = Virat_match_22_inning2.sort_values(by = 'ball')
Virat_match_22_inning4 = Virat_match_22_inning4.sort_values(by = 'ball')

Virat_match_22_inning2['cumsum_balls'] = [i for i in range(1, len(Virat_match_22_inning2) + 1)]
Virat_match_22_inning4['cumsum_balls'] = [i for i in range(1, len(Virat_match_22_inning4) + 1)]

Virat_match_22_inning2['Phases'] = Virat_match_22_inning2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_22_inning4['Phases'] = Virat_match_22_inning4.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_22_inning2 = Virat_match_22_inning2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_22_inning4 = Virat_match_22_inning4[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 23

In [75]:
Virat_match_23 = Virat[Virat.match_id == 1122276]
Virat_match_23_inning2 = Virat_match_23[Virat_match_23.innings == 2]
Virat_match_23_inning4 = Virat_match_23[Virat_match_23.innings == 4]

Virat_match_23_inning2 = Virat_match_23_inning2.sort_values(by = 'ball')
Virat_match_23_inning4 = Virat_match_23_inning4.sort_values(by = 'ball')

Virat_match_23_inning2['cumsum_balls'] = [i for i in range(1, len(Virat_match_23_inning2) + 1)]
Virat_match_23_inning4['cumsum_balls'] = [i for i in range(1, len(Virat_match_23_inning4) + 1)]

Virat_match_23_inning2['Phases'] = Virat_match_23_inning2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_23_inning4['Phases'] = Virat_match_23_inning4.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_23_inning2 = Virat_match_23_inning2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_23_inning4 = Virat_match_23_inning4[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 24

In [76]:
Virat_match_24 = Virat[Virat.match_id == 1122277]
Virat_match_24_inning2 = Virat_match_24[Virat_match_24.innings == 2]
Virat_match_24_inning4 = Virat_match_24[Virat_match_24.innings == 4]

Virat_match_24_inning2 = Virat_match_24_inning2.sort_values(by = 'ball')
Virat_match_24_inning4 = Virat_match_24_inning4.sort_values(by = 'ball')

Virat_match_24_inning2['cumsum_balls'] = [i for i in range(1, len(Virat_match_24_inning2) + 1)]
Virat_match_24_inning4['cumsum_balls'] = [i for i in range(1, len(Virat_match_24_inning4) + 1)]

Virat_match_24_inning2['Phases'] = Virat_match_24_inning2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_24_inning4['Phases'] = Virat_match_24_inning4.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_24_inning2 = Virat_match_24_inning2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_24_inning4 = Virat_match_24_inning4[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 25

In [77]:
Virat_match_25 = Virat[Virat.match_id == 1122278]
Virat_match_25_inning1 = Virat_match_25[Virat_match_25.innings == 1]
Virat_match_25_inning3 = Virat_match_25[Virat_match_25.innings == 3]

Virat_match_25_inning1 = Virat_match_25_inning1.sort_values(by = 'ball')
Virat_match_25_inning3 = Virat_match_25_inning3.sort_values(by = 'ball')

Virat_match_25_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_25_inning1) + 1)]
Virat_match_25_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_25_inning3) + 1)]

Virat_match_25_inning1['Phases'] = Virat_match_25_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_25_inning3['Phases'] = Virat_match_25_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_25_inning1 = Virat_match_25_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_25_inning3 = Virat_match_25_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 26

In [78]:
Virat_match_26 = Virat[Virat.match_id == 1122723]
Virat_match_26_inning1 = Virat_match_26[Virat_match_26.innings == 1]
Virat_match_26_inning3 = Virat_match_26[Virat_match_26.innings == 3]

Virat_match_26_inning1 = Virat_match_26_inning1.sort_values(by = 'ball')
Virat_match_26_inning3 = Virat_match_26_inning3.sort_values(by = 'ball')

Virat_match_26_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_26_inning1) + 1)]
Virat_match_26_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_26_inning3) + 1)]

Virat_match_26_inning1['Phases'] = Virat_match_26_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_26_inning3['Phases'] = Virat_match_26_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_26_inning1 = Virat_match_26_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_26_inning3 = Virat_match_26_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 27

In [79]:
Virat_match_27 = Virat[Virat.match_id == 1122724]
Virat_match_27 = Virat_match_27[Virat_match_27.innings == 2]

Virat_match_27 = Virat_match_27.sort_values(by = 'ball')

Virat_match_27['cumsum_balls'] = [i for i in range(1, len(Virat_match_27) + 1)]

Virat_match_27['Phases'] = Virat_match_27.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_27 = Virat_match_27[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 28

In [80]:
Virat_match_28 = Virat[Virat.match_id == 1122725]
Virat_match_28_inning1 = Virat_match_28[Virat_match_28.innings == 1]
Virat_match_28_inning3 = Virat_match_28[Virat_match_28.innings == 3]

Virat_match_28_inning1 = Virat_match_28_inning1.sort_values(by = 'ball')
Virat_match_28_inning3 = Virat_match_28_inning3.sort_values(by = 'ball')

Virat_match_28_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_28_inning1) + 1)]
Virat_match_28_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_28_inning3) + 1)]

Virat_match_28_inning1['Phases'] = Virat_match_28_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_28_inning3['Phases'] = Virat_match_28_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_28_inning1 = Virat_match_28_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_28_inning3 = Virat_match_28_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 29

In [81]:
Virat_match_29 = Virat[Virat.match_id == 1144993]
Virat_match_29_inning1 = Virat_match_29[Virat_match_29.innings == 1]
Virat_match_29_inning3 = Virat_match_29[Virat_match_29.innings == 3]

Virat_match_29_inning1 = Virat_match_29_inning1.sort_values(by = 'ball')
Virat_match_29_inning3 = Virat_match_29_inning3.sort_values(by = 'ball')

Virat_match_29_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_29_inning1) + 1)]
Virat_match_29_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_29_inning3) + 1)]

Virat_match_29_inning1['Phases'] = Virat_match_29_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_29_inning3['Phases'] = Virat_match_29_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_29_inning1 = Virat_match_29_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_29_inning3 = Virat_match_29_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 30

In [82]:
Virat_match_30 = Virat[Virat.match_id == 1144994]
Virat_match_30_inning2 = Virat_match_30[Virat_match_30.innings == 2]
Virat_match_30_inning4 = Virat_match_30[Virat_match_30.innings == 4]

Virat_match_30_inning2 = Virat_match_30_inning2.sort_values(by = 'ball')
Virat_match_30_inning4 = Virat_match_30_inning4.sort_values(by = 'ball')

Virat_match_30_inning2['cumsum_balls'] = [i for i in range(1, len(Virat_match_30_inning2) + 1)]
Virat_match_30_inning4['cumsum_balls'] = [i for i in range(1, len(Virat_match_30_inning4) + 1)]

Virat_match_30_inning2['Phases'] = Virat_match_30_inning2.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_30_inning4['Phases'] = Virat_match_30_inning4.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_30_inning2 = Virat_match_30_inning2[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_30_inning4 = Virat_match_30_inning4[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 31

In [83]:
Virat_match_31 = Virat[Virat.match_id == 1144995]
Virat_match_31_inning1 = Virat_match_31[Virat_match_31.innings == 1]
Virat_match_31_inning3 = Virat_match_31[Virat_match_31.innings == 3]

Virat_match_31_inning1 = Virat_match_31_inning1.sort_values(by = 'ball')
Virat_match_31_inning3 = Virat_match_31_inning3.sort_values(by = 'ball')

Virat_match_31_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_31_inning1) + 1)]
Virat_match_31_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_31_inning3) + 1)]

Virat_match_31_inning1['Phases'] = Virat_match_31_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_31_inning3['Phases'] = Virat_match_31_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_31_inning1 = Virat_match_31_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_31_inning3 = Virat_match_31_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 32

In [84]:
Virat_match_32 = Virat[Virat.match_id == 1144996]
Virat_match_32 = Virat_match_32[Virat_match_32.innings == 1]

Virat_match_32 = Virat_match_32.sort_values(by = 'ball')

Virat_match_32['cumsum_balls'] = [i for i in range(1, len(Virat_match_32) + 1)]

Virat_match_32['Phases'] = Virat_match_32.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_32 = Virat_match_32[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 33

In [85]:
Virat_match_33 = Virat[Virat.match_id == 1157752]
Virat_match_33 = Virat_match_33[Virat_match_33.innings == 1]

Virat_match_33 = Virat_match_33.sort_values(by = 'ball')

Virat_match_33['cumsum_balls'] = [i for i in range(1, len(Virat_match_33) + 1)]

Virat_match_33['Phases'] = Virat_match_33.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_33 = Virat_match_33[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 34

In [86]:
Virat_match_34 = Virat[Virat.match_id == 1157753]
Virat_match_34 =  Virat_match_34[Virat_match_34.innings == 2]

Virat_match_34 = Virat_match_34.sort_values(by = 'ball')

Virat_match_34['cumsum_balls'] = [i for i in range(1, len(Virat_match_34) + 1)]

Virat_match_34['Phases'] = Virat_match_34.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_34 = Virat_match_34[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 35

In [87]:
Virat_match_35 = Virat[Virat.match_id == 1187007]
Virat_match_35_inning1 = Virat_match_35[Virat_match_35.innings == 1]
Virat_match_35_inning3 = Virat_match_35[Virat_match_35.innings == 3]

Virat_match_35_inning1 = Virat_match_35_inning1.sort_values(by = 'ball')
Virat_match_35_inning3 = Virat_match_35_inning3.sort_values(by = 'ball')

Virat_match_35_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_35_inning1) + 1)]
Virat_match_35_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_35_inning3) + 1)]

Virat_match_35_inning1['Phases'] = Virat_match_35_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_35_inning3['Phases'] = Virat_match_35_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_35_inning1 = Virat_match_35_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_35_inning3 = Virat_match_35_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 36

In [88]:
Virat_match_36 = Virat[Virat.match_id == 1187008]
Virat_match_36 = Virat_match_36[Virat_match_36.innings == 1]

Virat_match_36 = Virat_match_36.sort_values(by = 'ball')

Virat_match_36['cumsum_balls'] = [i for i in range(1, len(Virat_match_36) + 1)]

Virat_match_36['Phases'] = Virat_match_36.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_36 = Virat_match_36[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 37

In [89]:
Virat_match_37 = Virat[Virat.match_id == 1187009]
Virat_match_37 = Virat_match_37[Virat_match_37.innings == 1]

Virat_match_37 = Virat_match_37.sort_values(by = 'ball')

Virat_match_37['cumsum_balls'] = [i for i in range(1, len(Virat_match_37) + 1)]

Virat_match_37['Phases'] = Virat_match_37.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_37 = Virat_match_37[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 38

In [90]:
Virat_match_38 = Virat[Virat.match_id == 1187016]
Virat_match_38 = Virat_match_38[Virat_match_38.innings == 2]

Virat_match_38 = Virat_match_38.sort_values(by = 'ball')

Virat_match_38['cumsum_balls'] = [i for i in range(1, len(Virat_match_38) + 1)]

Virat_match_38['Phases'] = Virat_match_38.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_38 = Virat_match_38[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 39

In [91]:
Virat_match_39 = Virat[Virat.match_id == 1187017]
Virat_match_39 = Virat_match_39[Virat_match_39.innings == 2]

Virat_match_39 = Virat_match_39.sort_values(by = 'ball')

Virat_match_39['cumsum_balls'] = [i for i in range(1, len(Virat_match_39) + 1)]

Virat_match_39['Phases'] = Virat_match_39.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_39 = Virat_match_39[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 40

In [92]:
Virat_match_40 = Virat[Virat.match_id == 1187685]
Virat_match_40_inning1 = Virat_match_40[Virat_match_40.innings == 1]
Virat_match_40_inning3 = Virat_match_40[Virat_match_40.innings == 3]

Virat_match_40_inning1 = Virat_match_40_inning1.sort_values(by = 'ball')
Virat_match_40_inning3 = Virat_match_40_inning3.sort_values(by = 'ball')

Virat_match_40_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_40_inning1) + 1)]
Virat_match_40_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_40_inning3) + 1)]

Virat_match_40_inning1['Phases'] = Virat_match_40_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_40_inning3['Phases'] = Virat_match_40_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_40_inning1 = Virat_match_40_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_40_inning3 = Virat_match_40_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 41

In [93]:
Virat_match_41 = Virat[Virat.match_id == 1187686]
Virat_match_41_inning1 = Virat_match_41[Virat_match_41.innings == 1]
Virat_match_41_inning3 = Virat_match_41[Virat_match_41.innings == 3]

Virat_match_41_inning1 = Virat_match_41_inning1.sort_values(by = 'ball')
Virat_match_41_inning3 = Virat_match_41_inning3.sort_values(by = 'ball')

Virat_match_41_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_41_inning1) + 1)]
Virat_match_41_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_41_inning3) + 1)]

Virat_match_41_inning1['Phases'] = Virat_match_41_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_41_inning3['Phases'] = Virat_match_41_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_41_inning1 = Virat_match_41_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_41_inning3 = Virat_match_41_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 42

In [94]:
Virat_match_42 = Virat[Virat.match_id == 1188628]
Virat_match_42_inning1 = Virat_match_42[Virat_match_42.innings == 1]
Virat_match_42_inning3 = Virat_match_42[Virat_match_42.innings == 3]

Virat_match_42_inning1 = Virat_match_42_inning1.sort_values(by = 'ball')
Virat_match_42_inning3 = Virat_match_42_inning3.sort_values(by = 'ball')

Virat_match_42_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_42_inning1) + 1)]
Virat_match_42_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_42_inning3) + 1)]

Virat_match_42_inning1['Phases'] = Virat_match_42_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_42_inning3['Phases'] = Virat_match_42_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_42_inning1 = Virat_match_42_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_42_inning3 = Virat_match_42_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

### Match 43

In [95]:
Virat_match_43 = Virat[Virat.match_id == 1188629]
Virat_match_43_inning1 = Virat_match_43[Virat_match_43.innings == 1]
Virat_match_43_inning3 = Virat_match_43[Virat_match_43.innings == 3]

Virat_match_43_inning1 = Virat_match_43_inning1.sort_values(by = 'ball')
Virat_match_43_inning3 = Virat_match_43_inning3.sort_values(by = 'ball')

Virat_match_43_inning1['cumsum_balls'] = [i for i in range(1, len(Virat_match_43_inning1) + 1)]
Virat_match_43_inning3['cumsum_balls'] = [i for i in range(1, len(Virat_match_43_inning3) + 1)]

Virat_match_43_inning1['Phases'] = Virat_match_43_inning1.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)
Virat_match_43_inning3['Phases'] = Virat_match_43_inning3.apply(lambda x: Phases_of_play(x['cumsum_balls']), axis = 1)


Virat_match_43_inning1 = Virat_match_43_inning1[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]
Virat_match_43_inning3 = Virat_match_43_inning3[['match_id','innings','bowling_team','runs_off_bat','ball','is_dot','is_four','is_six','cumsum_balls','Phases','Player_out']]

In [96]:
VK_2016_19 = pd.concat([Virat_match_1, Virat_match_2, Virat_match_3_inning1, Virat_match_3_inning3, Virat_match_4_inning1, Virat_match_4_inning3, Virat_match_5_inning1, Virat_match_5_inning3,Virat_match_6_inning1, Virat_match_6_inning3, Virat_match_7_inning2, Virat_match_7_inning4,Virat_match_8_inning1,Virat_match_8_inning3,Virat_match_9_inning2, Virat_match_9_inning4,Virat_match_10,Virat_match_11_1_inning1,Virat_match_11_1_inning3, Virat_match_12_inning2,Virat_match_12_inning4, Virat_match_13_inning1, Virat_match_13_inning3, Virat_match_14,Virat_match_15_inning1,Virat_match_15_inning3,Virat_match_16,Virat_match_17,Virat_match_18_inning2,Virat_match_18_inning4,Virat_match_19_inning1,Virat_match_19_inning3,Virat_match_20_inning1,Virat_match_20_inning3,Virat_match_21_inning2,Virat_match_21_inning4,Virat_match_22_inning2,Virat_match_22_inning4,Virat_match_23_inning2,Virat_match_23_inning4,Virat_match_24_inning2,Virat_match_24_inning4,Virat_match_25_inning1,Virat_match_25_inning3,Virat_match_26_inning1,Virat_match_26_inning3,Virat_match_27,Virat_match_28_inning1,Virat_match_28_inning3,Virat_match_29_inning1,Virat_match_29_inning3,Virat_match_30_inning2,Virat_match_30_inning4,Virat_match_31_inning1,Virat_match_31_inning3,Virat_match_32,Virat_match_33,Virat_match_34,Virat_match_35_inning1,Virat_match_35_inning3,Virat_match_36,Virat_match_37,Virat_match_38,Virat_match_39,Virat_match_40_inning1,Virat_match_40_inning3,Virat_match_41_inning1,Virat_match_41_inning3,Virat_match_42_inning1,Virat_match_42_inning3,Virat_match_43_inning1,Virat_match_43_inning3])

In [97]:
VK_2016_19

,match_id,innings,bowling_team,runs_off_bat,ball,is_dot,is_four,is_six,cumsum_balls,Phases,Player_out
910079,1022593,1,West Indies,0,27.5,1,0,0,1,First 25 balls,0
910078,1022593,1,West Indies,0,27.6,1,0,0,2,First 25 balls,0
910073,1022593,1,West Indies,3,28.5,0,0,0,3,First 25 balls,0
910071,1022593,1,West Indies,0,29.1,1,0,0,4,First 25 balls,0
910070,1022593,1,West Indies,0,29.2,1,0,0,5,First 25 balls,0
...,...,...,...,...,...,...,...,...,...,...,...
1201120,1188629,1,West Indies,0,70.6,1,0,0,160,Between 150-175 Balls,0
1201091,1188629,1,West Indies,0,71.3,1,0,0,161,Between 150-175 Balls,0
1201040,1188629,1,West Indies,1,71.4,0,0,0,162,Between 150-175 Balls,0
1201043,1188629,1,West Indies,0,72.1,1,0,0,163,Between 150-175 Balls,1
1202074,1188629,3,West Indies,0,20.2,1,0,0,1,First 25 balls,1

In [98]:
vk_1 = VK_2016_19.groupby(['Phases'])['runs_off_bat','is_dot','is_four','is_six','Player_out'].sum()

In [99]:
vk_2 = VK_2016_19.groupby(['Phases'])['match_id'].apply(lambda x: len(list(np.unique(x))))

In [100]:
vk_3 = VK_2016_19.groupby(['Phases'])['ball'].count()

In [101]:
Virat_2016_19 = pd.merge(vk_2,vk_1, on = 'Phases').merge(vk_3, on ='Phases').rename(columns = {'match_id':'Matches','runs_off_bat':'Runs','is_dot':'Dots','is_four':'Fours','is_six':'Sixes','Player_out':'Dismissals','ball':'Balls'})
Virat_2016_19

                       Matches  Runs  Dots  Fours  Sixes  Dismissals  Balls
Phases
Between 100-125 Balls       23   385   348     40      3           4    561
Between 125-150 Balls       19   301   279     35      0           2    448
Between 150-175 Balls       16   276   231     29      0           2    393
Between 175-200 Balls       15   244   218     22      1           2    368
Between 200-225 Balls       13   222   175     28      0           2    299
Between 225-250 Balls       11   169   136     18      2           3    230
Between 25-50 Balls         39   576   775     65      1          13   1088
Between 250-275 Balls        8   143    86     15      1           3    171
Between 275-300 Balls        5    75    49      7      0           2     97
Between 300-325 Balls        3    76    31      5      2           0     75
Between 325-350 Balls        3    44    26      3      1           1     54
Between 350-375 Balls        1    11    12      2      0           1     17
Between 50-75 Balls         31   487   604     52      0           6    888
Between 75-100 Balls        27   408   497     40      1           7    726
First 25 balls              43   814  1049     98      1          19   1469